<a href="https://colab.research.google.com/github/doyeonKoo/esaa/blob/main/3_8_%EA%B3%BC%EC%A0%9C_%EB%AC%B8%EC%A0%9C_Numpy_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
print(np.__version__)
print(np.show_config())

1.25.2
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS

#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
array1 = np.zeros(10)
array1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [4]:
# Using dtype() function

#### 5. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [5]:
array2 = np.zeros(10)
array2[4] = 1
array2

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 6. Create a vector with values ranging from 10 to 49 (★☆☆)

In [6]:
array3 = np.arange(10, 50)
array3

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 7. Reverse a vector (first element becomes last) (★☆☆)

In [7]:
array4 = array3[::-1]
array4

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 8. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [8]:
array5 = np.arange(0,9)
array5 = array5.reshape(3,3)
array5

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 9. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [9]:
array6 = np.array([1,2,0,0,4,0])
array6 = array6[array6!=0]
array6

array([1, 2, 4])

#### 10. Create a 3x3 identity matrix (★☆☆)
Hint : identity & eye, try to use 'help' to learn how to use two functions of numpy

In [10]:
?np.eye
?np.identity
array7 = np.eye(3)
array8 = np.identity(3)
print(array7,'\n', array8)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 11. Create a 3x3x3 array with random values (★☆☆)
Hint : numpy.random.random

In [11]:
array9 = np.random.random((3,3,3))
array9

array([[[0.79809488, 0.37014675, 0.01189585],
        [0.87949082, 0.08050012, 0.67511256],
        [0.44914463, 0.6043312 , 0.18315543]],

       [[0.65518527, 0.48299655, 0.57504519],
        [0.0165507 , 0.13305477, 0.59813701],
        [0.36566493, 0.08691764, 0.25270752]],

       [[0.4472912 , 0.6507022 , 0.01365502],
        [0.75832038, 0.69813078, 0.11943032],
        [0.12953436, 0.92665696, 0.55751847]]])

#### 12. Create a 10x10 array with random values and find the **min**imum and **max**imum values (★☆☆)

In [12]:
array10 = np.random.random((10,10))
print(array10.min(), array10.max())

0.005613389562713844 0.9955262851648481


#### 13. Create a random vector of size 30 and find the **mean** value (★☆☆)

In [13]:
array11 = np.random.random(30)
array11.mean()

0.48444890964153764

#### 14. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [14]:
array12 = np.ones([5,5])
array12[1:-1, 1:-1]=0
array12

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 15. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [15]:
0 * np.nan
#NaN
np.nan == np.nan
#FALSE
np.inf > np.nan
#FALSE
np.nan - np.nan
#NaN
np.nan in set([np.nan])
#True
0.3 == 3 * 0.1
#False

False

#### 16. Create a 5x5 matrix with values 1,2,3,4 just below the **diag**onal (★☆☆)

In [16]:
array16 = np.zeros((5,5))
def below_diag(x) :
    for i in range(5) :
        for j in range(5) :
            if (i-j)==1 :
                x[i][j] = i
    return x
below_diag(array16)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.]])

#### 17. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [17]:
array17 = np.zeros((8,8))
def ckbd(x) :
    for i in range(8) :
        for j in range(8) :
            if i%2==0 :
                if j%2!=0 :
                    x[i][j]=1
            else :
                if j%2 == 0:
                    x[i][j]=1
    return x
ckbd(array17)

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

#### 18. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
Hint : use 'numpy.unravel_index(value, (x, y, z))

In [18]:
?unravel_index
# 다차원 배열에서 일차원 인덱스를 다차원 인덱스로 변환하는 데 사용됩
array18 = np.unravel_index(99, (6,7,8))
array18

Object `unravel_index` not found.


(1, 5, 3)

#### 19. Normalize a 5x5 random matrix (★☆☆)
Hint : $Z = \frac{X - \overline{X}}{S}$

In [27]:
array19 = np.random.random((5,5))
z=(array19-np.mean(array19)) / (np.std(array19))
z

array([[ 0.53573401, -1.29254184,  1.45753507, -0.55867783, -0.33528479],
       [-1.21149788,  1.4690723 ,  1.10669155, -1.86321536, -1.09394896],
       [ 0.27595178,  0.56614249, -0.64844428, -1.53036338,  0.96608709],
       [-1.03896783,  0.66434587,  1.04059224,  1.66790973, -0.26310263],
       [ 0.79482162,  0.11270446, -0.20356949,  0.21556808, -0.83354203]])

#### 20. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
Hint : modify the code below
```python
numpy.dtype([(value, numpy.ubyte), … , (value, numpy.ubyte)])
```

In [28]:
array20 = np.dtype([('R', np.ubyte),('G', np.ubyte),
                    ('B',np.ubyte), ('A', np.ubyte)])
array20

dtype([('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')])

#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [29]:
array21 = np.random.random((5,3))
array211 = np.random.random((3,2))
np.dot(array21, array211)

array([[0.69289111, 1.20079632],
       [0.54757375, 0.86065933],
       [0.535559  , 1.05273274],
       [0.31009786, 0.64360656],
       [0.74213332, 0.99505193]])



```
# 코드로 형식 지정됨
```

#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [85]:
array22 = np.arange(20)
array22[(array22>=3) & (array22<=8)] *= -1
array22

array([ 0,  1,  2, -3, -4, -5, -6, -7, -8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [30]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [86]:
Z = np.array([1,2,3,4,5])
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
# Z<Z>Z is illegal

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [32]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

<ipython-input-32-cd809174da5d>:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
<ipython-input-32-cd809174da5d>:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)
<ipython-input-32-cd809174da5d>:3: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

In [33]:
?intersect1d
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
np.intersect1d(Z1,Z2)

array([0, 1, 3, 7])

#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [34]:
?emath
# It's False.
# 루트 안에 음수는 불가능하나, emath 모듈을 사용하여 가능케 함

#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

In [35]:
Z = np.arange('2016-07','2016-08', dtype = 'datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

In [36]:
def agg_fun(A,B) :
    x = np.multiply(np.add(A,B),np.divide((np.negative(A),2)))
    return x

#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

In [98]:
z = np.random.uniform(0, 100, 30)
# 방법 1
int = []
for i in range(len(z)) :
    if z[i] % 1 == 0 :
        int.append(z[i])
int

[]

In [99]:
z = np.random.uniform(0,100,30)
# 방법 2
int = []
for i in range(len(z)) :
    if z[i] // 1 == 0 :
        int.append(z[i])
int

[]

#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [37]:
array31 = np.random.random((5,5))
rowvalue = arange(0,5)
rowvalue
for i in range(5) :
    array31[i][:] = rowvalue
array31

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 32. Create a random vector of size 10 and sort it (★★☆)

In [38]:
array31 = np.random.random(10)
print(np.sort(array31))

[0.05079954 0.07022999 0.13839431 0.20463599 0.22399835 0.31686651
 0.55012024 0.75660862 0.80807845 0.82501846]


#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

In [39]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
np.array_equal(A,B)

False

#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

In [41]:
array34 = np.random.random((10,2))
array34[:, 0] = np.sqrt(array34[:, 0]**2 + array34[:, 1]**2)
array34[:, 1] = np.arctan2(array34[:, 1], array34[:, 0])
array34

array([[0.84277332, 0.64276084],
       [0.85285082, 0.78530434],
       [0.69255971, 0.67208783],
       [0.38647967, 0.651068  ],
       [0.59372402, 0.77591199],
       [0.90334874, 0.74801315],
       [0.78742479, 0.75401703],
       [1.10677267, 0.61131774],
       [0.48122563, 0.3397242 ],
       [0.92156532, 0.78171904]])

#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

In [42]:
Z=np.random.random(10)
Z[Z.argmax()]=0
Z

array([0.58870542, 0.27185561, 0.04386666, 0.57094338, 0.12321223,
       0.2343942 , 0.55261565, 0.48940086, 0.19476209, 0.        ])

#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

In [102]:
Z = np.arange(100)
v = np.random.uniform(0,100)
dist = np.abs(Z-v)
minindex = dist.argmin()
Z[minindex]

83

#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

In [47]:
# 배열의 요소와 색인을 반복적으로 제공
Z = np.arange(9).reshape(3,3)
Z
for index, value in np.ndenumerate(Z) :
    print(index, value)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

In [48]:
n = 10
p = 8
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'7')
print(Z)

[[0. 0. 7. 0. 0. 7. 0. 0. 0. 0.]
 [0. 0. 0. 0. 7. 0. 0. 0. 0. 7.]
 [0. 0. 0. 0. 7. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 7. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 7. 0. 0. 0. 7.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [107]:
Z = np.random.randint(0,10,(3,3))
Z

array([[9, 4, 7],
       [7, 1, 7],
       [1, 6, 7]])

In [109]:
# column 1
print(Z[Z[:, 0].argsort()])

[[1 6 7]
 [7 1 7]
 [9 4 7]]


In [110]:
# column 2
print(Z[Z[:, 1].argsort()])

[[7 1 7]
 [9 4 7]
 [1 6 7]]


In [111]:
# column 3
print(Z[Z[:, 2].argsort()])

[[9 4 7]
 [7 1 7]
 [1 6 7]]
